### ISSUE TITLE
User Story - Be controlled via phone

### ISSUE THREAD

**Issue by xunih** [DIT112-V19/group-06#26]
### User Story:
**As a:** tester

**I want:** the car to be tested via a mobile phone 

**So that:** I can control it conveniently

### Acceptance Criteria:
**I know I am done when:** the test is completely finished

**Comment by lichenyu99** [comment]
Related commit: Bluetooth-unfinished/Finished connection of bluetooth

**Comment by lichenyu99** [comment]
Done.
