### ISSUE TITLE
User Story - Deliver luggages at airport

### ISSUE THREAD

**Issue by lichenyu99** [DIT112-V19/group-06#29]
### User Story:
**As a:**  passenger

**I want:** to pick up my luggage at a specified spot within a specified time at the airport 

**So that:** I can save time of looking up my luggage on the carousel

### Acceptance Criteria:
**I know I am done when:** luggages are delivered to their specified spot

**Comment by platisd** [comment]
Why are these issues closed? Were they implemented? If so, where?

**Comment by flyslowly** [comment]
Some closed issues can not implement any more. And some are closed by mistake. They should be moved to Done.

**Comment by flyslowly** [comment]
The function has been implemented successfully.
