### ISSUE TITLE
User Story - Improve obstacle avoidance

### ISSUE THREAD

**Issue by flyslowly** [DIT112-V19/group-06#48]
### User Story:
**As a:**Passenger

**I want:**the car can choose a better another way when detecting an obstacle

**So that:**I can keep moving on 

### Acceptance Criteria:
**I know I am done when:**the car can turn around and forward to another direction after detecting an obstacle

**Comment by lichenyu99** [comment]
Related commit: Improve obstacle avoidance: keep moving

**Comment by lichenyu99** [comment]
Done.
