### ISSUE TITLE
User Story - Turn around when detecting obstacles 

### ISSUE THREAD

**Issue by xunih** [DIT112-V19/group-06#49]
### User Story:
**As a:** driver

**I want:** the car to turn to another direction when detecting obstacles

**So that:** I can keep moving without stopping

### Acceptance Criteria:
**I know I am done when:** the car turns around and moves forward

**Comment by lichenyu99** [comment]
Related commit: Updated LineFollowingAndObstacleAvoidance

**Comment by lichenyu99** [comment]
Done.
