### ISSUE TITLE
User Story - Integrate existing functions 

### ISSUE THREAD

**Issue by xunih** [DIT112-V19/group-06#72]
### User Story:
**As a:** user

**I want:** the car to move by following the line and stop automatically when detecting obstacles after hearing the voice command 

**So that:** I can control the car with multiple functions easily 

### Acceptance Criteria:
**I know I am done when:** all functions are implemented successfully

**Comment by lichenyu99** [comment]
Related commits: all the commits on 17th May

**Comment by xunih** [comment]
Done
